name: GitHub Action - IONIC

on:
  # Triggers the workflow on push or pull request events but only for the feature branches.
  push:
    branches: 
    - 'feature/*'
    - 'feature/**'
  pull_request:
    branches:
    - 'feature/*'
    - 'feature/**'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 

  # JOB to run change detection
  changes:
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Set job outputs to values from filter step
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    
    steps:
    # For pull requests it's not necessary to checkout the code
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - '!front-end/**'
            frontend:
              - 'front-end/**'

  # JOB to build and test backend code
  build-backend:

    needs: changes

    if: ${{ needs.changes.outputs.backend == 'true' }}
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checks-out repositorio
        uses: actions/checkout@v2

      - name: Configuración del entorno python
        uses: actions/setup-python@v2
        with:
            python-version: '3.8.10'
      
      - name: Instalación de dependencias
        run: |
          sudo apt-get install redis-server
          python -m pip install --upgrade pip
          python -m pip install -r flaskr/requirements.txt
    
      - name: Ejecución de pruebas unitarias
        run: |
          python -m unittest backtest/backtest.py
        
      - name: Analisis de cobertura
        run: |
          coverage run -m unittest backtest/backtest.py
          coverage report --include="flaskr/app.py,flaskr/vistas/*,flaskr/modelos/*,flaskr/helpers/*"
          
  # JOB to build and test frontend code
  build-frontend:

    needs: changes

    if: ${{ needs.changes.outputs.frontend == 'true' }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:            
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checks-out repositorio
        uses: actions/checkout@v2
          
  merge-feature-into-develop:

    needs: [build-backend, build-frontend]

    runs-on: ubuntu-latest

    steps:
      - name: Merge feature -> develop
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: develop
          github_token: ${{ github.token }}

#  merge-branch-release:

#    needs: build
#    runs-on: ubuntu-latest
#    if: startsWith(github.event.head_commit.message, 'RELEASE')
#    steps:
      
#      - name: Delete branch release
#        uses: dawidd6/action-delete-branch@v3
#        with:
#          github_token: ${{github.token}}
#          branches: release

#      - name: merge-branch-release 
#        uses: peterjgrainger/action-create-branch@v2.0.1
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
#        with:
#          branch: 'release'
            
#  merge-branch-main:
  
#    needs: merge-branch-release
#    runs-on: ubuntu-latest
#    steps:

#      - name: Merge staging -> uat
#        uses: devmasx/merge-branch@v1.3.1
#        with:
#          type: now
#          from_branch: release
#          target_branch: main
#          github_token: ${{ github.token }}
